

<form method="post" action="<?php echo App::config('url') ?>Index/newPost" enctype='multipart/form-data'>

    <div class="form-group">
        <label for="content">What's on your mind?</label>
        <input id="content" name="content">
        <label for="image">Upload picture</label>
        <input type="file" id="image" name="image">
    </div>

    <button type="submit" name="submit" class="btn btn-primary">Add new post</button>

</form>



<?php foreach ($posts as $post): ?>
    <!-- Post values -->
    <p>
        Post:
        <a href="<?php echo App::config('url') ?>Index/view/<?= $post->getId() ?> ">
            <?php echo htmlspecialchars($post->getContent()); ?>
        </a>

        Created at:
        <?php
        //date value
        $date = new DateTime($post->getDate());
        echo $date->format('d.m.Y.  H:i') . "<br>";
        //img value if exists
        if($post->getImage() != '') {
            echo "Img: <br>" .
                "<img src=" . htmlspecialchars($post->getImage()) . " height=100px; width=100px;>";
        }
        //comments
        $i = 0;
        foreach ($comments as $comment){
            if($post->getId() === $comment->getIdPost()){
                $i = $i + 1;
            }
        }
        if($i === 0){
            echo "there are no comments for this post.";
        } else {
            echo "number of comments: " . $i;
        }




        ?>
    </p>
    <!-- end post values -->
    <form method="post" action="<?php echo App::config('url') ?>Index/newComment/<?php echo $post->getId() ?>">

        <div class="form-group">
            <label for="content">add new comment for post</label>
            <input id="content" name="content">
            <button type="submit" name="submit" class="btn btn-primary">Comment</button>
        </div>



    </form>
<?php endforeach; ?>
<?php

?>

