

<form method="post" action="<?php echo App::config('url') ?>Index/newPost" enctype='multipart/form-data'>

    <div class="form-group">
        <label for="content">What's on your mind?</label>
        <input id="content" name="content">
        <label for="image">Upload picture</label>
        <input type="file" id="image" name="image">
    </div>

    <button type="submit" name="submit" class="btn btn-primary">Save</button>

</form>



<?php foreach ($posts as $post): ?>
    <p>
        Post:
        <a href="<?php echo App::config('url') ?>Index/view/<?= $post->getId() ?> ">
            <?php echo htmlspecialchars($post->getContent()); ?>
        </a>
        Created at:
        <?php
        $date = new DateTime($post->getDate());
        echo $date->format('d.m.Y.  H:i') . "<br>";
        ?>
        Img:
        <img src="<?php echo htmlspecialchars($post->getImage()); ?>" height="100px;" width="100px;">

    </p>
<?php endforeach; ?>




