<h2>
    POST:
    <?= htmlspecialchars($post->getContent()) ?></h2>
    CREATED AT:
    <?= htmlspecialchars($post->getDate()). "<br>" ?></p>
    <?php
    if($post->getImage() != '') {
    echo "Img: <br>" .
    "<img src=../../" . htmlspecialchars($post->getImage()) . " height=100px; width=100px;>";
    } else {
      echo  "ovaj post nema sliku =(";
    }
    ?>



<h3>Comments</h3>

<?php
foreach ($comment as $com) {
    echo $com->getContent(). "<br>";
}
?>